name: Preview Environments Workflow

on:
  pull_request:
    types: [opened, closed]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check event type
        run: echo "${{ github.event.action }}"

      - name: Set preview environment env
        if: ${{ endsWith(github.ref, '-preview-env') }}
        run: echo "PREVIEW_ENV_ID=$(echo $GITHUB_REF_NAME | awk -F'/' '{print $2}' | awk -F'-' '{print $1}')" >> $GITHUB_ENV

      - name: Create preview environment (PR opened)
        if: github.event.action == 'opened'
        run: |
          echo "Hi"

      - name: Delete preview environment (PR closed)
        if: github.event.action == 'closed'
        run: |
          echo "Goodbye"
