name: Preview Environments Workflow

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  create-or-delete:
    if: ${{ endsWith(github.ref, '-preview-env') }}
    runs-on: ubuntu-latest
    env:
      PREVIEW_ENV_ID: ${{ github.event.number }}

    steps:
      - name: Create preview environment (PR opened)
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: dotnet run --project ./platform/tools/PreviewEnvCli -- create -i $PREVIEW_ENV_ID

      - name: Delete preview environment (PR closed)
        if: github.event.action == 'closed'
        run: dotnet run --project ./platform/tools/PreviewEnvCli -- delete -i $PREVIEW_ENV_ID
